server {
    listen 80;

    # Tentukan lokasi file website
    root /usr/share/nginx/html;

    # File default yang akan disajikan
    index index.html;

    location / {
        # Coba cari file yang sesuai dengan URI yang diminta.
        # Jika tidak ada, coba cari folder yang sesuai.
        # Jika masih tidak ada, kembalikan 'index.html'.
        try_files $uri $uri/ /index.html;
    }
}